[Add education component]Add education component in city file
gallettilance/CS506-Fall2020 pull request #73
Opened 2020-09-12 01:15 UTC by zhou-1

Education component includes 3 parts with image shows.

2020-09-14 12:56 UTC, gallettilance requested changes
Why did you change the `city.py` file? You should implement your functions in their respective files.

2020-09-14 13:21 UTC, zhou-1 commented
> Why did you change the `city.py` file? You should implement your functions in their respective files.

I thought we can "implement" it whatever we want, I will make a change...

2020-09-14 14:22 UTC, zhou-1 commented
Just deleted the images and changed back to original city file. Also added school and library to city.

2020-09-14 14:50 UTC, gallettilance commented
@zhou-1 the images are great actually please feel free to use them. I just ask that you implement that inside their respective files instead of in `city.py`.

2020-09-14 15:07 UTC, zhou-1 commented
> @zhou-1 the images are great actually please feel free to use them. I just ask that you implement that inside their respective files instead of in `city.py`.

@gallettilance I see, just added images and modified the function a little bit. Hope this will make it better. :)

2020-09-14 15:53 UTC, gallettilance requested changes

2020-09-14 15:53 UTC, gallettilance commented on 01-python/education/library.py
> +img = Image.open("library.png")
needs an indent

2020-09-14 15:53 UTC, gallettilance commented on 01-python/education/library.py
> +    print("+---------------------------------------------------------+")
this indent is also off

2020-09-14 15:53 UTC, gallettilance commented on 01-python/education/school.py
> +    print("+---------------------------------------------------------+")
this indent is off

2020-09-14 15:53 UTC, gallettilance commented on README.md
> +The Final Project Repository can be found [here](https://github.com/BU-Spark/CS506-Fall2020-Projects)
please remove these changes

2020-09-14 16:10 UTC, zhou-1 commented on 01-python/education/library.py
> +img = Image.open("library.png")
I don't know why, but they are all looking good in my editor...

2020-09-14 16:11 UTC, zhou-1 commented on README.md
> +The Final Project Repository can be found [here](https://github.com/BU-Spark/CS506-Fall2020-Projects)
I will do that.

2020-09-14 18:14 UTC, gallettilance requested changes

2020-09-14 18:14 UTC, gallettilance commented on README.md
> +Finish exercise 3
It's the opposite that is needed - you should not add the exercise 3 work here.

2020-09-14 18:17 UTC, zhou-1 commented on README.md
> +Finish exercise 3
My bad, changed!

2020-09-15 15:36 UTC, gallettilance requested changes

2020-09-15 15:36 UTC, gallettilance commented on README.md
> -The Final Project Repository can be found [here](https://github.com/BU-Spark/CS506-Fall2020-Projects)
please add these deleted lines back so that you are not changing the readme when this merges

2020-09-15 15:36 UTC, gallettilance commented
also please squash your commits

2020-09-15 17:45 UTC, zhou-1 reviewed
> also please squash your commits

@gallettilance Not sure whether I did it correctly, I tried " git rebase -i --root" ("git rebase -i HEAD~N" doesn't work for me)....

2020-09-16 15:48 UTC, gallettilance requested changes

2020-09-16 15:48 UTC, gallettilance commented on e -i --root
> +[33mcommit 365d21091e7d6d3262f9ff185b49546907a7dd70[m[33m ([m[1;36mHEAD -> [m[1;32mcomponent-branch[m[33m, [m[1;31morigin/component-branch[m[33m)[m
please remove this file

2020-09-16 15:48 UTC, gallettilance commented on README.md
> +___
please remove this change

2020-09-16 19:30 UTC, zhou-1 commented on README.md
> +___
I don't know why this happened, I changed.

2020-09-16 22:03 UTC, gallettilance requested changes
Great work! Just need to remove that strange root file and I will approve your PR

2020-09-16 23:39 UTC, zhou-1 commented
> Great work! Just need to remove that strange root file and I will approve your PR

@gallettilance I deleted it before I git add, commit and push; it is still here? :(

2020-09-17 16:37 UTC, zhou-1 commented
> Great work! Just need to remove that strange root file and I will approve your PR

@gallettilance I pushed again, hope this time it works!

2020-09-19 00:17 UTC, zhou-1 commented
Please let me know whether it works. :)

2020-09-19 00:17 UTC, closed without merging